version: '3'
services: 
  nodejsdockerpractice: #docker run -it -v ${PWD}:/work -w /work -p 5002:5000 bal/nodejsdockerpractice:1.0.0 /bin/sh
    container_name: nodejsdockerpractice
    image: bal/nodejsdockerpractice:1.0.0
    build: ./nodejsdockerpractice
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./nodejsdockerpractice/src/:/work
    ports:
      - 5002:5000


